### ISSUE TITLE
Publish to Nuget

### ISSUE THREAD

**Issue by kingboyk** [kingboyk/Serilog.NodaTime#4]

**Comment by kingboyk** [comment]
The 2 commits referencing this issue on 17 Feb should have refererenced #1

**Comment by feitzi** [comment]
Can you please publish the package to nuget? This would be awesome :)

**Comment by kingboyk** [comment]
Hi, Thanks for the interest. Sure, I'll try and get this done asap.

**Comment by kingboyk** [comment]
@feitzi The package is now available on [Nuget](https://www.nuget.org/packages/Serilog.NodaTime/). Please let me know if you have any problems.

**Comment by feitzi** [comment]
Perfect, I will try it out after Easter. Thank you :)
